language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

env:
  - REQUIREMENTS=lowest PACKAGING=true STYLE=true
  - REQUIREMENTS=release PACKAGING=true STYLE=true
  - REQUIREMENTS=devel PACKAGING=true STYLE=true

matrix:
  exclude:
    - python: 2.6
      env: REQUIREMENTS=lowest PACKAGING=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=release PACKAGING=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=devel PACKAGING=true STYLE=true
  include:
    - python: 2.6
      env: REQUIREMENTS=lowest DOCUMENTATION=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=release DOCUMENTATION=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=devel DOCUMENTATION=true STYLE=true
    - python: pypy
      env: REQUIREMENTS=lowest DOCUMENTATION=true
    - python: pypy
      env: REQUIREMENTS=release DOCUMENTATION=true
    - python: pypy
      env: REQUIREMENTS=devel DOCUMENTATION=true
  allow_failures:
    - python: pypy
      env: REQUIREMENTS=lowest PACKAGING=true STYLE=true
    - python: pypy
      env: REQUIREMENTS=release PACKAGING=true STYLE=true
    - python: pypy
      env: REQUIREMENTS=devel PACKAGING=true STYLE=true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --use-mirrors pytest pytest-cov selenium tox coveralls sphinx invoke
  - pip install .

script:
  - invoke travis

after_success:
  - coveralls
