language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

env:
  - REQUIREMENTS=lowest PACKAGING=true
  - REQUIREMENTS=release PACKAGING=true
  - REQUIREMENTS=devel PACKAGING=true

matrix:
  exclude:
    - python: 2.6
      env: REQUIREMENTS=lowest PACKAGING=true
    - python: 2.6
      env: REQUIREMENTS=release PACKAGING=true
    - python: 2.6
      env: REQUIREMENTS=devel PACKAGING=true
  include:
    - python: 2.6
      env: REQUIREMENTS=lowest DOCUMENTATION=true
    - python: 2.6
      env: REQUIREMENTS=release DOCUMENTATION=true
    - python: 2.6
      env: REQUIREMENTS=devel DOCUMENTATION=true

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --use-mirrors pytest pytest-cov tox coveralls sphinx
  - pip install .

script:
  - py.test --cov=flask_relief --cov=test_flask_relief.py
  - tox -e style
  # ensure that the docs stuff runs only once
  - [[ $DOCUMENTATION == true ]] && tox -e docs
  - [[ $DOCUMENTATION == true ]] && tox -e docs3
  - [[ $DOCUMENTATION == true ]] && tox -e docs-linkcheck
  - [[ $PACKAGING == true ]] && tox -e packaging

after_success:
  - coveralls
