language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --use-mirrors pytest pytest-cov tox coveralls

script:
  - py.test --cov=flask_relief --cov=test_flask_relief.py
  - tox -e style
  - python -c "import sys; sys.exit(sys.version_info[:2] > (2, 6))" || tox -e packaging

after_success:
  - coveralls
