language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

env:
  - REQUIREMENTS=lowest PACKAGING=true STYLE=true
  - REQUIREMENTS=release PACKAGING=true STYLE=true
  - REQUIREMENTS=devel PACKAGING=true STYLE=true

matrix:
  exclude:
    - python: 2.6
      env: REQUIREMENTS=lowest PACKAGING=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=release PACKAGING=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=devel PACKAGING=true STYLE=true
  include:
    - python: 2.6
      env: REQUIREMENTS=lowest DOCUMENTATION=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=release DOCUMENTATION=true STYLE=true
    - python: 2.6
      env: REQUIREMENTS=devel DOCUMENTATION=true STYLE=true
    - python: pypy
      env: REQUIREMENTS=lowest DOCUMENTATION=true
    - python: pypy
      env: REQUIREMENTS=release DOCUMENTATION=true
    - python: pypy
      env: REQUIREMENTS=devel DOCUMENTATION=true
  allow_failures:
    - python: pypy
      env: REQUIREMENTS=lowest PACKAGING=true STYLE=true
    - python: pypy
      env: REQUIREMENTS=release PACKAGING=true STYLE=true
    - python: pypy
      env: REQUIREMENTS=devel PACKAGING=true STYLE=true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --use-mirrors pytest pytest-cov selenium tox coveralls sphinx
  - pip install .

script:
  - py.test --cov=flask_relief --cov=tests
  - if [[ STYLE = true ]]; then tox -e style; fi
  # ensure that the docs stuff runs only once
  - if [[ DOCUMENTATION = true ]]; then tox -e docs; fi
  - if [[ DOCUMENTATION = true ]]; then tox -e docs3; fi
  - if [[ DOCUMENTATION = true ]]; then tox -e docs-linkcheck; fi
  - if [[ PACKAGING = true ]]; then tox -e packaging; fi

after_success:
  - coveralls
