# coding: utf-8
"""
    flask.ext.relief.crypto
    ~~~~~~~~~~~~~~~~~~~~~~~

    :copyright: 2013 by Daniel Neuhäuser
    :license: BSD, see LICENSE.rst for details
"""
import os

from flask.ext.relief._compat import int_to_byte


def xor_bytes(a, b):
    """
    XORs each byte in `a` and `b` together and returns the concatenated result.
    """
    return b''.join(
        int_to_byte(x ^ y) for x, y in zip(bytearray(a), bytearray(b))
    )


def encrypt_once(plaintext):
    """
    Returns a random key and the ciphertext of a one-time pad, generated using
    the returned key and the given `plaintext`. Expects everything to be bytes.
    """
    key = os.urandom(len(plaintext))
    return key, xor_bytes(key, plaintext)


def decrypt_once(key, ciphertext):
    """
    Decrypts a one-time pad as generated by :func:`encrypt_once` and returns
    the plaintext.
    """
    return xor_bytes(key, ciphertext)
